export const SAVE_CONTACT = "SAVE_CONTACT";
export const SORT_CONTACTS = "SORT_CONTACTS";
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const COMMON_SEARCH = "COMMON_SEARCH";
export const UPDATE_CONTACT = "UPDATE_CONTACT"